version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.8.1-python3.10
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ../petroleum_pipeline:/opt/airflow/dbt/petroleum_pipeline
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    ports:
      - "5432:5432"

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install dbt-snowflake==1.11.3 &&
        airflow db migrate &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname Rahul \
          --lastname Tiwary \
          --role Admin \
          --email rahul@example.com
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: bash -c "pip install dbt-snowflake==1.11.3 && airflow webserver"
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: bash -c "pip install dbt-snowflake==1.11.3 && airflow scheduler"
    restart: always

volumes:
  postgres-db-volume:
